# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Md Golam Morshed
tagline:          'Md Golam Morshed'
description:      'PhD Candidate at UVA'
url:              http://mgmorshed.github.io
#baseurl:          /

author:
  name:           'Md Golam Mrosehd'
  #url:            http://mgmorshed.github.io

logo:             /assets/img/photo_golam_3.jpg

#paginate:         5
gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-gist, jekyll-include-cache]

plugins:
  - jekyll-paginate
  - jekyll-include-cache


# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/mgmorshed/mgmorshed.github.io

tags:

email_username: 'mm8by@virginia.edu'
#github_username:  mgmorshed
scholar_username: 'https://scholar.google.com/citations?user=N_i37NQAAAAJ&hl=en'
linkedin_username: golam-morshed-3050b0177

